### ISSUE TITLE
Website online zetten

### ISSUE THREAD

**Issue by stgm** [minprog/platforms#39]

**Comment by stgm** [comment]
@Jelleas @simonpauw Kunnen jullie even inloggen op platforms21 om een admin-account te krijgen?
Ik zal de webhook aanzetten zodat de site update bij elke commit.

**Comment by Jelleas** [comment]
![image](https://user-images.githubusercontent.com/1257775/123423704-2bc99380-d5c0-11eb-80f5-9d61423ce28a.png)

@stgm

**Comment by stgm** [comment]
OK OK met je screenshot
